### ISSUE TITLE
Github Checks sometimes fail if too many characters sent in request

### ISSUE THREAD

**Issue by mehagar** [reviewdog/action-brakeman#16]
I started to see this message in some of my brakeman checks:

```
reviewdog: post failed for brakeman: failed to post result: PATCH api.github.com/repos/schooladmin/schooladmin/check-runs/1929969266: 422 Invalid request.

Only 65535 characters are allowed; 68496 were supplied. []
```

Here is the workflow config file I am using:

```yaml
name: brakeman
on: [pull_request]
jobs:
  brakeman:
    name: runner / brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          github_token: ${{ secrets.github_token }}
```

<details>
<summary>Details</summary>

</details>
