### ISSUE TITLE
Error: Process completed with exit code 3 but no PR comments

### ISSUE THREAD

**Issue by carl-printreleaf** [reviewdog/action-brakeman#38]
Using the following config on Github Actions:
```yaml
name: reviewdog
on: [pull_request]
jobs:
  brakeman:
    name: runner / brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: 4.10.1
          reporter: github-pr-review # Default is github-pr-check
```
Github Actions outputs:
```
Error: Process completed with exit code 3.
```
But does not add pull request comments on a line of code that brakeman complains about locally.

**Comment by bogn83** [comment]
Same here, could only make use of the action and not let it fail our builds with this extra config:
```
          brakeman_flags: '--no-exit-on-warn --no-exit-on-error'
```

actually it is
```
          fail_on_error: true
          brakeman_flags: '--no-exit-on-warn --no-exit-on-error'
```
now which seems to contradict on first sight (fail on error but no exit on error) but to my understanding it tells the brakeman process itself not to exit (this being the problem of this issue 38 here) but the action to report with failure and not just a warning hidden in the checks tab.

**Comment by carl-printreleaf** [comment]
@bogn83 that's helpful thanks

**Comment by Mason-Seeger** [comment]
I have a brakeman action set up as follows:

```
brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: 4.8.2
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true
          brakeman_flags: --skip-files app/jobs/some_file_name.rb
```

This results in the action getting to the `Running brakeman with reviewdog 🐶 ...` step and only logging out `Error: Process completed with exit code 7.` I have not really been able to find anything on what exit code 7 means and there is no indication as to what the issue might be from the error.

Additionally, using the reviewdog/action-brakeman@v1 with all the same configurations results in the `reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128` error that has been a problem with many reviewdog repos that started in the last 24 hours or so.
