### ISSUE TITLE
Two GitHub checks for each job

### ISSUE THREAD

**Issue by dbackeus** [reviewdog/action-brakeman#5]
This seems confusing:
<img width="851" alt="Screenshot 2020-06-24 at 14 38 23" src="https://user-images.githubusercontent.com/3461/85558382-fb57be00-b628-11ea-8278-55d6f56c856f.png">

The brakeman is failing in this case, yet there is one check which is still reporting green.

Is this intentional?

Workflow yml used:
```yml
name: main
on: pull_request
jobs:
  brakeman:
    name: runner / brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          brakeman_version: 4.8.2
          github_token: ${{ secrets.github_token }}

```

**Comment by LaurenceGA** [comment]
Pretty sure this is intentional.
I think this is to do with the way the Github [Checks API](https://developer.github.com/v3/checks/) works an interacts with workflows. 
The [default reporter for this action is `github-pr-check`](https://github.com/reviewdog/action-brakeman/blob/2aa538ac8a32115011da41edda5fe7aa934b4e07/action.yml#L23). That means that the results of the action will be reported as a _new check_. That's the one that you're seeing that's failing.
The workflow itself has its own check for whether it ran successfully.
So on check saying is that the workflow (and hence brakeman/reviewdog) ran successfully, the other one is saying that brakeman/reviewdog's check itself didn't pass.

You can see a [list of reporters](https://github.com/reviewdog/reviewdog#reporters) here that you can use as an alternative if you like.

(Please correct be if I'm wrong @haya14busa)

**Comment by mgrachev** [comment]
> Would make more sense to me if the report was sent as part of the "parent" action. That's how most other GitHub actions I've tried work.

You can try using the different reporter - `github-pr-review`. You will get a result similar to [this one](https://github.com/reviewdog/action-brakeman#with-github-pr-review):
```yaml
name: reviewdog
on: [pull_request]
jobs:
  brakeman:
    name: runner / brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          brakeman_version: 4.8.2
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
```
