### ISSUE TITLE
How to work with PRs from forked repos?

### ISSUE THREAD

**Issue by mehagar** [reviewdog/action-brakeman#7]
I forked a private repo, then tested that action-brakeman works when creating PRs from the forked repo to the same repo. I also tested it when creating a PR from the upstream repo to the upstream repo. So it works when creating PRs with both target and source branches in the same repo. But for PRs with the source branch in the fork and the target in the upstream repo, the Action never runs.

How can I fix this? Here is my workflow file:

```yaml
name: reviewdog
on: [pull_request]
jobs:
  brakeman:
    name: runner / brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          brakeman_version: 4.8.2
          github_token: ${{ secrets.github_token }}
```
